FROM python:3.12-slim

RUN apt-get update -y && \
    apt-get install -y curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd --create-home appuser
USER appuser

RUN mkdir -p /home/appuser/app


WORKDIR /home/appuser/app/

# Install uv and add to PATH
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/home/appuser/.cargo/bin:$PATH"

# Copy source files for building
COPY --chown=appuser:appuser . /home/appuser/app/

# Install dependencies and build the package
RUN uv pip install .

ENTRYPOINT ["python", "/home/appuser/app/main.py"]